"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const inventoryService_1 = require("./services/inventoryService");
const Product_1 = require("./classes/Product");
const User_1 = require("./classes/User");
const userService_1 = require("./services/userService");
const product1 = new Product_1.Product("1", "Szék", 1500, "leírás");
const product2 = new Product_1.Product("2", "Asztal", 1500, "leírás");
const inventory = new inventoryService_1.Inventory([]);
inventory.addProduct(product1);
inventory.addProduct(product2);
const user = new User_1.User("user1", "Alice Smith", "alice@example.com");
const userService = new userService_1.UserService;
console.log("Termékek listázása");
console.log(inventory.listAllProducts());
console.log("Alice vásárol.");
const placeAnOrder = userService.placeAnOrder(inventory, "1");
console.log(placeAnOrder ? "Sikeres vásárlás!" : "Termék nem található.");
console.log("Termékek listázása vásárlás után");
console.log(inventory.listAllProducts());
